services:
  web:
    image: nginx:alpine
    ports:
      - "81:80"
    volumes:
      - ./index.php:/var/www/html/index.php
      - ./nginx-conf/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    image: php:fpm
    volumes:
      - ./index.php:/var/www/html/index.php