version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  
  php:
    image: php:fpm
    container_name: php-container
    volumes:
      - ./html:/usr/share/nginx/html

networks:
  default:
    driver: bridge
