<?php

namespace ContainerT1y2wqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ProductController' shared autowired service.
     *
     * @return \App\Controller\ProductController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'ProductController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Product'.\DIRECTORY_SEPARATOR.'ProductRepository.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Product'.\DIRECTORY_SEPARATOR.'PersistenceInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Product'.\DIRECTORY_SEPARATOR.'JsonFileAdapter.php';

        $container->services['App\\Controller\\ProductController'] = $instance = new \App\Controller\ProductController(new \App\Product\ProductRepository(new \App\Product\JsonFileAdapter((\dirname(__DIR__, 4).'/var/products.json'))));

        $instance->setContainer(($container->privates['.service_locator.Cg6rAV4'] ?? $container->load('get_ServiceLocator_Cg6rAV4Service'))->withContext('App\\Controller\\ProductController', $container));

        return $instance;
    }
}
