# Makefile to automate the creation and display of myname.txt

# Target to create the file with name and surname
create:
	echo "Bouddehbine Jaouad" > myname.txt

# Target to display the content of the file
display:
	cat myname.txt

# Default target to run both the above targets
all: create display
