services:
  web:
    image: nginx:alpine
    depends_on:
      - php-container
    ports:
      - 81:80
    volumes:
      - ./:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  php-container:
    image: php:fpm
    volumes:
      - ./:/usr/share/nginx/html
