services:

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d
      - ./src:/var/www/html
    networks:
      - net
  
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - net
    volumes:
      - ./src:/var/www/html
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini

  maria-db:
    image: mariadb
    volumes:
      - ./db://var/lib/mysql
    networks:
      - net
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

networks:
  net:
    driver: bridge
