# config/services.yaml
services:
    _defaults:
        autowire: true      # Injection automatique des dépendances
        autoconfigure: true # Autoconfiguration des services
        public: false       # Les services sont privés par défaut

    # Configuration du contrôleur
    App\Controller\ProductController:
        public: true
        arguments:
            $productAdapter: '@App\Service\ProductAdapter'

    # Configuration de ProductAdapter
    App\Service\ProductAdapter:
        arguments:
            $persistence: '@App\Persistence\ProductPersistenceInterface'

    # Configuration de SqlPersistence
    App\Persistence\SqlPersistence:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'

    # Configuration de JsonPersistence
    App\Persistence\JsonPersistence:
        arguments:
            $filePath: '%kernel.project_dir%/data/products.json'

    # Liaison de l'interface ProductPersistenceInterface avec SqlPersistence
    App\Persistence\ProductPersistenceInterface: '@App\Persistence\SqlPersistence'

    # Ajout de cette ligne pour garantir que HelloWorldController est bien configuré
    App\Controller\HelloWorldController:
        tags: ['controller.service_arguments']
