services:
  web:
    image: nginx:alpine
    ports:
      - "80.:80" # Expose host port 81 to container port 80
    depends_on:
      - php # Ensure PHP service starts before web service
    volumes:
      - ./:/var/www/html # Mount the current directory as the web root
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # Mount the nginx.conf file

  php:
    image: php:fpm
    volumes:
      - ./:/var/www/html # Mount the current directory as the web root