
services:
  web:
    image: nginx:alpine
    ports:
      - "81:80"  # Expose le port 81 de l'hôte au port 80 du conteneur
    depends_on:
      - php  # Assure que le service PHP est démarré avant le service web
    volumes: 
      - ./:/var/www/html  # Monte le répertoire actuel comme racine web
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # nginx.conf file

  php:
    image: php:fpm
    volumes:
      - ./:/var/www/html  # Monte le répertoire actuel comme racine web
    # Ajoutez les variables d'environnement nécessaires pour l'application PHP